# Generated by Django 5.0 on 2025-10-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
    ]
