# Generated by Django 5.0 on 2025-09-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movierequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierequest',
            old_name='description',
            new_name='movie_description',
        ),
        migrations.RenameField(
            model_name='movierequest',
            old_name='title',
            new_name='movie_name',
        ),
    ]
